feat: add executing block num to apm
nervosnetwork/muta pull request #429
Opened 2020-08-24 04:52 UTC by KaoImin

**What this PR does / why we need it**:
Add executing block number gauge to apm.

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

2020-08-24 05:15 UTC, yejiayu commented
Don't forget the doc https://github.com/nervosnetwork/muta/blob/master/common/apm/README.md @KaoImin

2020-08-24 05:23 UTC, yejiayu requested changes
I don't quite understand your logic.

It seems to me that you only need to collect metrics once each time a new task is inserted into the execution queue and once each time the task is executed.

2020-08-24 07:33 UTC, homura commented
Wouldn't it be clearer to just monitor the current `exec_height`?

I'm guessing that `executing_blocks` is trying to see how many blocks have been executed in a single execution, and is essentially monitoring how many blocks are currently behind, right? 

Therefore, I suggest that just monitoring `exec_height` is sufficient and we can build a module to monitor the current backward height

```
muta_consensus_commited_height - muta_consensus_executed_height
```

2020-08-25 06:25 UTC, LycrusHamster approved these changes

2020-08-25 06:25 UTC, merged